use troveweb;

#Order query, won't include shipping labels as that may be limiting
select
  UO.ORDERID,
  UA.FIRST_NAME,
  UA.USERNAME,
  UA.EMAIL,
  UO.CHECKOUTEMAIL,
  CI.FROZENITEMNAME,
  CI.ENGRAVETEXT,
  CI.ACTUAL_PRICE AS ITEM_PRICE,
  CA.SHOULDBEGIFTWRAPPED,
  CA.INCLUDEGIFTMESSAGECARD,
  CA.GIFTMESSAGECARDTEXT,
  UO.GRAND_TOTAL,
  UO.ORDER_DATE,
  UO.ORDERSTATUS,
  PO.MANUFACTURERORDERID AS SHAPEWAYS_ORDER_NUMBER,
  UO.TROVE_ORDER_NUMBER,
  CI.CARTITEMSTATUS,
  PO.STATUS AS PRINTORDER_STATUS,
  CI.PROTOTYPEREQUESTED,
  CI.MATERIAL_NAME,
  CI.FINISH_NAME,
  CI.CARTITEMID,
  CI.PROTOTYPEEMAILSTATE,
  IT.ITEMID,
  ADDRESS.ADDRESS_LINE_1,
  ADDRESS.ADDRESS_LINE_2,
  ADDRESS.CITY,
  ST.`NAME` AS STATE,
  ADDRESS.POSTAL_CODE,
  IC.SIZE AS ITEM_SIZE,
  PO.MODELURL AS OBJ_LINK,
  PO.PRINTORDERPRIMARYKEYID AS PRINT_ORDER_ID
from `ORDER` UO JOIN ORDER_ORDERITEMS OIJOIN ON UO.ORDERID = OIJOIN.ORDERID_OID
  JOIN ORDER_CARTREFERENCE CR ON UO.ORDERID=CR.ORDERID_OID
  JOIN CART CA ON CA.CARTID=CR.CARTID_ID
  JOIN CARTITEM CI ON OIJOIN.CARTITEMID_EID = CI.CARTITEMID
  JOIN USER_ACCOUNTS UA ON UA.USERID=UO.ORDERS
  JOIN CARTITEM_CARTITEMREFERENCE CIR ON CIR.CARTITEMID_OID=CI.CARTITEMID
  JOIN ITEM IT ON CIR.ITEMID_ID=IT.ITEMID
  JOIN PRINTORDER PO ON PO.CARTITEMREFERENCE_CARTITEMID_OID=CI.CARTITEMID
  JOIN ORDER_SHIPPINGADDRESS BA ON BA.ORDERID_OID=UO.ORDERID
  JOIN ADDRESS ON ADDRESS.ADDRESSID=BA.ADDRESSID_ID
  JOIN ADDRESS_SUBDIVISION STJ ON STJ.ADDRESSID_OID=ADDRESS.ADDRESSID
  JOIN SUBDIVISION ST ON ST.PRIMARYKEYID=STJ.PRIMARYKEYID_ID
  JOIN ITEMCUSTOMIZATION IC ON CUSTOMIZATIONS_CARTITEMID_OWN=CI.CARTITEMID
WHERE IC.SIZE is not null #AND CI.CARTITEMID in (53, 117)
ORDER BY UO.ORDERID ASC;

#Shipping label query, won't include orders that don't have labels generated
select
  UO.ORDERID,
  UA.FIRST_NAME,
  UA.USERNAME,
  UA.EMAIL,
  UO.CHECKOUTEMAIL,
  CI.FROZENITEMNAME,
  CI.ENGRAVETEXT,
  CI.ACTUAL_PRICE AS ITEM_PRICE,
  UO.GRAND_TOTAL,
  UO.ORDER_DATE,
  UO.ORDERSTATUS,
  LABEL.`STATUS` AS SHIPPING_STATUS,
  LABEL.TRACKINGNUMBER AS TRACKING_NUMBER,
  LABEL.LABELURL AS LABEL_DOWNLOAD,
  PO.MANUFACTURERORDERID AS SHAPEWAYS_ORDER_NUMBER,
  UO.TROVE_ORDER_NUMBER,
  CI.CARTITEMSTATUS,
  CI.PROTOTYPEREQUESTED,
  CI.CARTITEMID,
  IT.ITEMID,
  ADDRESS.ADDRESS_LINE_1,
  ADDRESS.ADDRESS_LINE_2,
  ADDRESS.CITY,
  ST.`NAME` AS STATE,
  ADDRESS.POSTAL_CODE
from `ORDER` UO JOIN ORDER_ORDERITEMS OIJOIN ON UO.ORDERID = OIJOIN.ORDERID_OID
  JOIN CARTITEM CI ON OIJOIN.CARTITEMID_EID = CI.CARTITEMID
  JOIN USER_ACCOUNTS UA ON UA.USERID=UO.ORDERS
  JOIN CARTITEM_CARTITEMREFERENCE CIR ON CIR.CARTITEMID_OID=CI.CARTITEMID
  JOIN ITEM IT ON CIR.ITEMID_ID=IT.ITEMID
  JOIN PRINTORDER PO ON PO.CARTITEMREFERENCE_CARTITEMID_OID=CI.CARTITEMID
  JOIN EASYPOSTPOSTAGELABEL LABEL ON LABEL.PRINTLABELS_PRINTORDERPRIMARYKEYID_OWN=PO.PRINTORDERPRIMARYKEYID
  JOIN ORDER_SHIPPINGADDRESS BA ON BA.ORDERID_OID=UO.ORDERID
  JOIN ADDRESS ON ADDRESS.ADDRESSID=BA.ADDRESSID_ID
  JOIN ADDRESS_SUBDIVISION STJ ON STJ.ADDRESSID_OID=ADDRESS.ADDRESSID
  JOIN SUBDIVISION ST ON ST.PRIMARYKEYID=STJ.PRIMARYKEYID_ID
  JOIN ITEMCUSTOMIZATION IC ON CUSTOMIZATIONS_CARTITEMID_OWN=CI.CARTITEMID
WHERE UA.EMAIL not like "%@troveup.com%" AND IC.SIZE is not null
ORDER BY UO.ORDERID ASC;

#Gift Cards Query
select `OR`.ORDERID, UA.USERNAME AS PURCHASER_USERNAME, UA.EMAIL AS PURCHASER_EMAIL, `OR`.ORDER_DATE, `OR`.SHOULDBEGIFTWRAPPED, `OR`.GIFTMESSAGECARDTEXT, GC.AMOUNT AS GIFT_CARD_AMOUNT,
  GC.DIGITAL, GC.EMAILDATE, GC.FROMEMAIL, GC.FROMNAME, GC.TOEMAIL, GC.TONAME, GC.GIFTCARDSTRING AS GIFTCARD, SA.ADDRESS_LINE_1, SA.ADDRESS_LINE_2, SA.CITY, SA.POSTAL_CODE, `OR`.GRAND_TOTAL AS ORDER_TOTAL from `ORDER` `OR`
  JOIN ORDER_GENERICITEMSLIST GIL ON `OR`.ORDERID = GIL.ORDERID_OID
  JOIN GENERICITEM GI ON GIL.GENERICITEMID_EID = GI.GENERICITEMID
  JOIN GIFTCARD GC ON GI.GENERICITEMID = GC.GENERICITEMREFERENCE_GENERICITEMID_OID
  JOIN USER_ACCOUNTS UA ON UA.USERID=`OR`.ORDERS
  JOIN ORDER_SHIPPINGADDRESS SAJ ON `OR`.ORDERID = SAJ.ORDERID_OID
  JOIN ADDRESS SA ON SAJ.ADDRESSID_ID = SA.ADDRESSID;

#Necklace Query
select
  UO.ORDERID,
  UA.FIRST_NAME,
  UA.USERNAME,
  UA.EMAIL,
  UO.CHECKOUTEMAIL,
  CI.FROZENITEMNAME,
  CI.ENGRAVETEXT,
  CI.ACTUAL_PRICE AS ITEM_PRICE,
  CA.SHOULDBEGIFTWRAPPED,
  CA.INCLUDEGIFTMESSAGECARD,
  CA.GIFTMESSAGECARDTEXT,
  UO.GRAND_TOTAL,
  UO.ORDER_DATE,
  UO.ORDERSTATUS,
  PO.MANUFACTURERORDERID AS SHAPEWAYS_ORDER_NUMBER,
  UO.TROVE_ORDER_NUMBER,
  CI.CARTITEMSTATUS,
  PO.STATUS AS PRINTORDER_STATUS,
  CI.PROTOTYPEREQUESTED,
  CI.MATERIAL_NAME,
  CI.FINISH_NAME,
  CI.CARTITEMID,
  CI.PROTOTYPEEMAILSTATE,
  CI.CHAIN_CHAINID_OID,
  CH.NAME AS CHAIN,
  IT.ITEMID,
  ADDRESS.ADDRESS_LINE_1,
  ADDRESS.ADDRESS_LINE_2,
  ADDRESS.CITY,
  ST.`NAME` AS STATE,
  ADDRESS.POSTAL_CODE,
  PO.MODELURL AS OBJ_LINK,
  PO.PRINTORDERPRIMARYKEYID AS PRINT_ORDER_ID
from `ORDER` UO JOIN ORDER_ORDERITEMS OIJOIN ON UO.ORDERID = OIJOIN.ORDERID_OID
  JOIN ORDER_CARTREFERENCE CR ON UO.ORDERID=CR.ORDERID_OID
  JOIN CART CA ON CA.CARTID=CR.CARTID_ID
  JOIN CARTITEM CI ON OIJOIN.CARTITEMID_EID = CI.CARTITEMID
  JOIN USER_ACCOUNTS UA ON UA.USERID=UO.ORDERS
  JOIN CARTITEM_CARTITEMREFERENCE CIR ON CIR.CARTITEMID_OID=CI.CARTITEMID
  JOIN ITEM IT ON CIR.ITEMID_ID=IT.ITEMID
  JOIN PRINTORDER PO ON PO.CARTITEMREFERENCE_CARTITEMID_OID=CI.CARTITEMID
  JOIN ORDER_SHIPPINGADDRESS BA ON BA.ORDERID_OID=UO.ORDERID
  JOIN ADDRESS ON ADDRESS.ADDRESSID=BA.ADDRESSID_ID
  JOIN ADDRESS_SUBDIVISION STJ ON STJ.ADDRESSID_OID=ADDRESS.ADDRESSID
  JOIN SUBDIVISION ST ON ST.PRIMARYKEYID=STJ.PRIMARYKEYID_ID
  JOIN CHAIN AS CH ON CI.CHAIN_CHAINID_OID = CH.CHAINID
WHERE IT.CATEGORY="NECKLACE"
ORDER BY UO.ORDERID ASC;

#Query for showing items that have no plastic models and have been delivered
select
  UO.ORDERID,
  UA.FIRST_NAME,
  UA.USERNAME,
  UA.EMAIL,
  UO.CHECKOUTEMAIL,
  CI.FROZENITEMNAME,
  CI.ENGRAVETEXT,
  CI.ACTUAL_PRICE AS ITEM_PRICE,
  CA.SHOULDBEGIFTWRAPPED,
  CA.INCLUDEGIFTMESSAGECARD,
  CA.GIFTMESSAGECARDTEXT,
  UO.GRAND_TOTAL,
  UO.ORDER_DATE,
  UO.ORDERSTATUS,
  PO.MANUFACTURERORDERID AS SHAPEWAYS_ORDER_NUMBER,
  UO.TROVE_ORDER_NUMBER,
  CI.CARTITEMSTATUS,
  PO.STATUS AS PRINTORDER_STATUS,
  CI.PROTOTYPEREQUESTED,
  CI.MATERIAL_NAME,
  CI.FINISH_NAME,
  CI.CARTITEMID,
  CI.PROTOTYPEEMAILSTATE,
  IT.ITEMID,
  ADDRESS.ADDRESS_LINE_1,
  ADDRESS.ADDRESS_LINE_2,
  ADDRESS.CITY,
  LABEL.`STATUS` AS SHIPPING_STATUS,
  LABEL.TRACKINGNUMBER AS TRACKING_NUMBER,
  LABEL.LABELURL AS LABEL_DOWNLOAD,
  ST.`NAME` AS STATE,
  ADDRESS.POSTAL_CODE,
  IC.SIZE AS ITEM_SIZE,
  PO.MODELURL AS OBJ_LINK,
  PO.PRINTORDERPRIMARYKEYID AS PRINT_ORDER_ID,
  IT.ORIGINFTUE AS FROM_FTUE
from `ORDER` UO JOIN ORDER_ORDERITEMS OIJOIN ON UO.ORDERID = OIJOIN.ORDERID_OID
  JOIN ORDER_CARTREFERENCE CR ON UO.ORDERID=CR.ORDERID_OID
  JOIN CART CA ON CA.CARTID=CR.CARTID_ID
  JOIN CARTITEM CI ON OIJOIN.CARTITEMID_EID = CI.CARTITEMID
  JOIN USER_ACCOUNTS UA ON UA.USERID=UO.ORDERS
  JOIN CARTITEM_CARTITEMREFERENCE CIR ON CIR.CARTITEMID_OID=CI.CARTITEMID
  JOIN ITEM IT ON CIR.ITEMID_ID=IT.ITEMID
  JOIN PRINTORDER PO ON PO.CARTITEMREFERENCE_CARTITEMID_OID=CI.CARTITEMID
  JOIN ORDER_SHIPPINGADDRESS BA ON BA.ORDERID_OID=UO.ORDERID
  JOIN ADDRESS ON ADDRESS.ADDRESSID=BA.ADDRESSID_ID
  JOIN ADDRESS_SUBDIVISION STJ ON STJ.ADDRESSID_OID=ADDRESS.ADDRESSID
  JOIN EASYPOSTPOSTAGELABEL LABEL ON LABEL.PRINTLABELS_PRINTORDERPRIMARYKEYID_OWN=PO.PRINTORDERPRIMARYKEYID
  JOIN SUBDIVISION ST ON ST.PRIMARYKEYID=STJ.PRIMARYKEYID_ID
  JOIN ITEMCUSTOMIZATION IC ON CUSTOMIZATIONS_CARTITEMID_OWN=CI.CARTITEMID
WHERE (IC.SIZE is not null OR IT.CATEGORY="NECKLACE") AND (PO.STATUS = "COMPLETE" AND MATERIAL_NAME != "Try-On")
GROUP BY CARTITEMID
ORDER BY UO.ORDERID ASC;

#Query that gives only order items that are owned by the user
select
  UO.ORDERID,
  UA.USERID,
  IT.ITEMOWNER_USERID_OID AS ITEM_OWNER_ID,
  UA.FIRST_NAME,
  UA.USERNAME,
  UA.EMAIL,
  UO.CHECKOUTEMAIL,
  CI.FROZENITEMNAME,
  CI.ENGRAVETEXT,
  CI.ACTUAL_PRICE AS ITEM_PRICE,
  UO.GRAND_TOTAL,
  UO.ORDER_DATE,
  UO.ORDERSTATUS,
  PO.MANUFACTURERORDERID AS SHAPEWAYS_ORDER_NUMBER,
  UO.TROVE_ORDER_NUMBER,
  CI.CARTITEMSTATUS,
  PO.STATUS AS PRINTORDER_STATUS,
  CI.PROTOTYPEREQUESTED,
  CI.MATERIAL_NAME,
  CI.FINISH_NAME,
  CI.CARTITEMID,
  CI.PROTOTYPEEMAILSTATE,
  IT.ITEMID,
  PO.MODELURL AS OBJ_LINK,
  PO.PRINTORDERPRIMARYKEYID AS PRINT_ORDER_ID,
  IT.ORIGINFTUE AS FROM_FTUE
FROM `CARTITEM` CI JOIN CART CA ON CI.CART_CARTID_OID = CA.CARTID
  JOIN ORDER_ORDERITEMS OIJOIN ON OIJOIN.CARTITEMID_EID = CI.CARTITEMID
  JOIN `ORDER` UO ON UO.ORDERID = OIJOIN.ORDERID_OID
  JOIN ORDER_CARTREFERENCE CR ON UO.ORDERID=CR.ORDERID_OID
  JOIN USER_ACCOUNTS UA ON UA.USERID=UO.ORDERS
  JOIN PRINTORDER PO ON PO.CARTITEMREFERENCE_CARTITEMID_OID=CI.CARTITEMID
  JOIN ITEMCUSTOMIZATION IC ON CUSTOMIZATIONS_CARTITEMID_OWN=CI.CARTITEMID
  JOIN CARTITEM_CARTITEMREFERENCE CIR ON CIR.CARTITEMID_OID=CI.CARTITEMID
  JOIN ITEM IT ON CIR.ITEMID_ID=IT.ITEMID
WHERE IT.ITEMOWNER_USERID_OID = UA.USERID
GROUP BY CARTITEMID
ORDER BY UO.ORDERID ASC;